name: Simple CI

on:
  push:
    branches:
      - main

jobs:
  toto:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run a one-line script
        run: echo "Hello, world !"
