name: Simple CI

on:
  push:
    branches:
      - main

jobs:
  toto:
    runs-on: ubuntu-latest

    steps:

      - name: Run a one-line script
        run: echo "Hello, world !"

  tutu:
    runs-on: ubuntu-latest

    steps:

      - name: Run a one-line script
        run: echo "Bybye, world !"
