name: Simple CI

on:
  workflow_dispatch:

jobs:
  titi:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          repository: apellegr06/reusable-ci-example
          
      - name: action
        uses : ./../../apellegr06/reusable-ci-example/.github/actions
    
