name: Simple CI

on:
  workflow_dispatch:

jobs:
  toto:
    runs-on: ubuntu-latest
    environment: prd

    steps:

      - name: Run a one-line script
        run: echo "Hello, world ! ${{ vars.VAR1 }} = ${{ vars.VAR2 }}"

  tutu:
    runs-on: ubuntu-latest

    steps:

      - name: Run a one-line script
        run: echo "Bybye, world !"

  tata:
    needs: [toto,tutu]
    runs-on: ubuntu-latest

    steps:

      - name: Run a one-line script
        run: echo "Bybye, world !"
